# Archivo con la configuración de Travis CI, sistema
#   de integración continua

# Sólo se ejecuta con Python 3.5
language: python
python:
  - "3.5"

# Hay que instalar las dependencias
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

# Estos son los tests que se ejecutarán
script:
    - flake8
    - pytest

# Lanza página para medir cobertura
# Se puede ver en https://codecov.io/gh/abertal/alpha
after_success:
    - bash <(curl -s https://codecov.io/bash)
